### ISSUE TITLE
Add timers for seaweed & cactus patches

### ISSUE THREAD

**Issue by gytosas** [queicherius/runelite-time-tracking-reminder#10]

**Comment by queicherius** [comment]
For seaweed, do you farm it generally or do you do it with your birdhouse runs?

Also do you farm specifically cactus or is it for the farming contracts (in which case, does the farming contract info box work for you)?

Hespori is already ready & tested, coming in the next update (#9)

**Comment by gytosas** [comment]
Nice, keep it up.
I mean it would be beneficial to add each type of plants, and check those which u want to track
•••options to group all plants on 1 timer
••• option to check only those u want track ,like every checked plant has its own timer
Example. if u check "group special patches" it groups all those timers to 1, and shows up when all plants ar ready to harvest.
Or u could check "has its own timer" and check those specificly u want to track. like fruit tree, herbs, seaweed,  cactus and each of them have their own tracker.
Idk if its possible or its to hard, but it would be cool.
By special patches i mean cactus/ mushrooms/belladona/ seaweed/ hardwood tree and etc. 
Would like to have seaweed/cactus on its own and not with birdhouses/farming contracts.

**Comment by queicherius** [comment]
Seaweed is now available in `1.3.0` thanks to #12

**Comment by queicherius** [comment]
Cactus implemented in #19, coming in `1.4.0`
