### ISSUE TITLE
spirit trees keep the tree patches as ready

### ISSUE THREAD

**Issue by Orimazer** [queicherius/runelite-time-tracking-reminder#11]
i just use the spirit trees for transport, not to dig up and farm repeatedly. however having a grown spirit tree makes it so the tree patch info box is always "ready", even if no other tree patch is.

**Comment by queicherius** [comment]
Interesting! I can't currently debug this because I don't have the farming level for spirit trees yet. What does the official time tracking plugin from RuneLite show in the sidebar here?

![image](https://user-images.githubusercontent.com/4615516/170533676-988546f2-dc6a-4c36-a460-792d7da5570d.png)

**Comment by Orimazer** [comment]
it shows as "Done"
![image](https://user-images.githubusercontent.com/16553650/170552251-6bc3415e-8e06-46ac-b495-b4b9a99faec3.png)

**Comment by queicherius** [comment]
I think you can solve the issue by going into the settings for "Time Tracking" and turning this option off:

![image](https://user-images.githubusercontent.com/4615516/170738029-a7ca4d84-b6d7-4f11-a79b-f4f5648d2f56.png)

This essentially turns the functionality from "show an infobox when *any* trees are ready" (checked) to "show an infobox when *all* trees are ready" (unchecked).

Let me know if that works for you :)

**Comment by Orimazer** [comment]
yeah, that seems to work, sorry to have bothered you for a setting i didn't see

**Comment by queicherius** [comment]
Awesome! No worries, I added a note about this to the readme. 👍
