### ISSUE TITLE
Different ways of showing Ready status

### ISSUE THREAD

**Issue by Gollum69** [queicherius/runelite-time-tracking-reminder#32]
Currently the "Ready" text extends beyond the infobox size, and causes overlapping when placing the infoboxes next to each other. With the amount of infoboxes we all use nowadays it can interfere with the layouts and other infoboxes we use, so I would really like different ways of showing the infobox being ready.

Some options I can propose are showing a green dot instead of text, displaying the letter 'R' instead of 'Ready', or the border of the infobox becoming green when its ready with or without displaying any text.

**Comment by queicherius** [comment]
The best-case would probably just an option where you can type the text in that should be shown (so you can put in "R" / "Rdy" / "⬤"). Would go well together with #31 to cut the amount of infoboxes.

**Comment by queicherius** [comment]
Implemented by #45
