### ISSUE TITLE
Stopped working after todays update

### ISSUE THREAD

**Issue by AlperSzr** [queicherius/runelite-time-tracking-reminder#34]
The plugin has stopped working for me after todays update

**Comment by YvesW** [comment]
As a side note, this is very likely due to https://github.com/runelite/runelite/commit/02aad2f9d4f0c8a09c68799a20e65b144bc3a6a1

**Comment by queicherius** [comment]
Turns out the fix was very quick, should be live: https://github.com/runelite/plugin-hub/pull/4043
