### ISSUE TITLE
Why birdhouses ready -infobox is separated from everything else?

### ISSUE THREAD

**Issue by ZeiZeiii** [queicherius/runelite-time-tracking-reminder#35]
![image](https://user-images.githubusercontent.com/123414249/227300799-dbddd89e-d1e6-47ce-af3a-a4bc4f4f9461.png)

**Comment by queicherius** [comment]
You can `Alt` + `Click` move the infoboxes individually to where you would like them to be :)

**Comment by queicherius** [comment]
I believe you can reset it to be in it's original group with some combination of `Alt` / `Ctrl` / `Click` and `Right Click` but I am not sure which one it was.

**Comment by ZeiZeiii** [comment]
Oh, did not knew that. Now idea how it got detached. Thank you! :)
