### ISSUE TITLE
All info boxes show up

### ISSUE THREAD

**Issue by elwakka** [queicherius/runelite-time-tracking-reminder#36]
Fresh install.  But it seems like every single info box says "ready" - the normal time tracker plugin shows nothing is ready besides some compost.

**Comment by queicherius** [comment]
We also show "Ready" when nothing is planed in the spot (since you have to go there and do something). Is that the case?

**Comment by elwakka** [comment]
Yes, that is the case. Interesting.

**Comment by queicherius** [comment]
👍 That's intended then. You can disable the ones you can't do yet in the settings :)
