### ISSUE TITLE
Request toggleable display on text

### ISSUE THREAD

**Issue by DoilCoding** [queicherius/runelite-time-tracking-reminder#40]
Can you make it so we can toggle between showing and hiding the "Ready" ontop of the infobox?
Or at least able to scale the size of the text cause when altering the runelite font and infobox settings it is quite ugly to look at.

Besides that I love the plugin <3

![image](https://user-images.githubusercontent.com/37671244/234570670-39c37772-215f-4dc9-af74-2718cd2389f7.png)

**Comment by queicherius** [comment]
Duplicate of https://github.com/queicherius/runelite-time-tracking-reminder/issues/32
