### ISSUE TITLE
Plugin is not updating

### ISSUE THREAD

**Issue by pidbullz** [queicherius/runelite-time-tracking-reminder#44]
I've been using it for nearly idk 6 months, no issues. But today as I started RL it just wont refresh, i get to patches or birdhouses but it just says its ready, contracts etc dont refresh. So ill turn it off for now :/

**Comment by queicherius** [comment]
I dont play OSRS anymore, but I just logged in and did a quick birdhouse run and my ready disappeared, so I can't reproduce this. If anyone else has this issue please comment here.

**Comment by pidbullz** [comment]
Update: after pc, jagex launcher and original Time Tracking resetting, it appears to work again. I think the TT one bugged out somehow and TTR thus didnt work. Ty for your reply tho, and no worries it was just me then!
