### ISSUE TITLE
giant compost bin isnt right

### ISSUE THREAD

**Issue by post-async** [queicherius/runelite-time-tracking-reminder#53]
![image](https://github.com/queicherius/runelite-time-tracking-reminder/assets/34499002/da0786e5-fe1e-4702-bbd7-9fbfd91a62e8)

this bin is NOT ready :O

**Comment by post-async** [comment]
i think you gotta change https://github.com/queicherius/runelite-time-tracking-reminder/blob/85c49dcc8cfaf43b11639b54a3feb97602c28fc6/src/main/java/com/timetrackingreminder/TimeTrackingReminderPlugin.java#L209 to something like 
`farmingTracker.getSummary(Tab.GIANT_COMPOST) != SummaryState.COMPLETED` but i dont know how to test plugin hub plugins with local changes so im not making the PR

**Comment by queicherius** [comment]
did it show as ready in the normal farming tracker?

**Comment by post-async** [comment]
not the big compost bin, no
![image](https://github.com/queicherius/runelite-time-tracking-reminder/assets/34499002/03f15b46-5741-4b56-a949-8653526f1692)

**Comment by queicherius** [comment]
Then it's intentional - the bin is "ready" because you have to do something: fill it & close it.
