### ISSUE TITLE
Farming Contract reminder

### ISSUE THREAD

**Issue by AnkouOSRS** [queicherius/runelite-time-tracking-reminder#6]
Not sure how annoying this would be to implement, but it would be really nice to have a reminder for when whatever your farming contract is finishes.

**Comment by queicherius** [comment]
The data is in a bit of a different format, but it looks doable. I'll likely get to this when I start doing medium contracts, which should be fairly soon.

**Comment by queicherius** [comment]
Implementation for this is done, will be updated on the Plugin Hub soon

**Comment by queicherius** [comment]
Updated on the Plugin Hub now, version `1.1.0` 🎉
