### ISSUE TITLE
Herbs constantly show as ready

### ISSUE THREAD

**Issue by DiogenesCow** [queicherius/runelite-time-tracking-reminder#62]
I'm not sure for how long its been like this, maybe a couple of days, but its in the corner constantly showing ready when I've finished a run and after. Tried to turn it off and on in settings, deactivate and activate herblore, reinstalling the plugin, its still there.

**Comment by Notloc** [comment]
Works fine for me.
Did you perhaps adjust the `Prefer soonest completion` setting in `Time Tracking`?
It effects how this plugin displays what is ready.

(I'm not referring to this plugin's settings, but rather the original Time Tracking plugin that ships with Runelite.)

**Comment by DiogenesCow** [comment]
> Works fine for me. Did you perhaps adjust the `Prefer soonest completion` setting in `Time Tracking`? It effects how this plugin displays what is ready.
> 
> (I'm not referring to this plugin's settings, but rather the original Time Tracking plugin that ships with Runelite.)

I had it turned off and I checked the settings and the prefer soonest completion is unchecked. I turned it on again, checked the prefer soonest completion, and now its working again! Thanks for the help :)
