### ISSUE TITLE
Anima Patches show incorrectly

### ISSUE THREAD

**Issue by elwakka** [queicherius/runelite-time-tracking-reminder#64]
Anima patches show in infobox as  "Dead" "Yo ur anima patch is ready for replacement" however nothing has ever been planted in it (I don't even have the level to get to it).

Time tracker normal runelite pluin has it being empty and saying "Done".

I'm currently on the setting "Only show harvestable" -> but clicking the box both shows the anima patch as "Dead" no matter what.

![image](https://github.com/queicherius/runelite-time-tracking-reminder/assets/67753396/e49b1970-8f10-4047-9e5a-55b6452b22e1)

**Comment by queicherius** [comment]
This is currently intentional - if it's empty it assumes you have to do something to fix it. You can disable it until you have the level for it :)
