### ISSUE TITLE
Ignore Farming and Celastrus Tree

### ISSUE THREAD

**Issue by mcgeer** [queicherius/runelite-time-tracking-reminder#68]
Recent update had celastrus tree selected, however I have Ignore Farming Guild so it shouldn't have displayed. Please ignore if they added a new patch and I didn't know.

**Comment by queicherius** [comment]
This was recently added as an extra option since it's on a different timer than other tree. You can just disable the option :)

**Comment by mcgeer** [comment]
That's what I did, wasn't sure if it was a bug or not
